theme = "catppuccin_macchiato"

[editor]
line-number = "relative"
text-width = 100
cursorline = true
bufferline = "multiple"
rulers = [100]
idle-timeout = 0
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
character = "|"
render = true

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name"]
center = []
right = ["selections", "primary-selection-length", "position", "position-percentage", "spacer", "diagnostics", "workspace-diagnostics"]

[keys.normal]
"A-," = "goto_previous_buffer"
"A-." = "goto_next_buffer"
"A-W" = ":buffer-close"
"A-/" = "repeat_last_motion"
"A-x" = "extend_to_line_bounds"
"X" = ["extend_line_up", "extend_to_line_bounds"]
"ret" = ["open_below", "normal_mode"] # Enter adds line above
"*" = ["move_next_word_end", "move_prev_word_start", "search_selection"]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.select]
"A-x" = "extend_to_line_bounds"
"X" = ["extend_line_up", "extend_to_line_bounds"]
