# Python
[[language]]
name = "python"
roots = ["pyproject.toml", "pyrightconfig.json", ".git"]
language-servers = ["pyright", "ruff"]
auto-format = true
indent = { tab-width = 4, unit = "    " }

[language.formatter]
command = "ruff"
args = ["format", "--line-length=88", "-"]

[language-server.pyright]
command = "pyright-langserver"
args = ["--stdio"]

[language-server.pyright.config.python.analysis]
typeCheckingMode = "basic"
autoImportCompletions = true
reportMissingTypeStubs = false

[language-server.ruff]
command = "ruff-lsp"


# Rust
[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
scope = "source.rust"
injection-regex = "rust"
file-types = ["rs"]
indent = { tab-width = 4, unit = "    " }
auto-format = true


# TypeScript
[[language]]
name = "typescript"
language-servers = ["typescript-language-server"]
auto-format = true

# JavaScript
[[language]]
name = "javascript"
language-servers = ["typescript-language-server"]
auto-format = true

# HTML
[[language]]
name = "html"
language-servers = ["vscode-html-language-server"]

# CSS
[[language]]
name = "css"
language-servers = ["vscode-css-language-server"]

# JSON
[[language]]
name = "json"
language-servers = ["vscode-json-language-server"]


# LSP configurations
[language-server.typescript-language-server]
command = "typescript-language-server"
args = ["--stdio"]

[language-server.vscode-html-language-server]
command = "vscode-html-language-server"
args = ["--stdio"]

[language-server.vscode-css-language-server]
command = "vscode-css-language-server"
args = ["--stdio"]

[language-server.vscode-json-language-server]
command = "vscode-json-language-server"
args = ["--stdio"]
